-- Dashboard locaux pharma - schema Supabase/PostgreSQL cible.
-- Idempotent sur une base neuve et sur le schema locaux_dash deja en production.
-- A executer comme proprietaire du projet. Aucun utilisateur Auth n'est auto-inscrit.

begin;

create schema if not exists extensions;
create extension if not exists btree_gist with schema extensions;

-- Corrige l'installation historique dans public sans casser les objets qui l'utilisent.
do $migration$
begin
  if exists (
    select 1
    from pg_extension e
    join pg_namespace n on n.oid = e.extnamespace
    where e.extname = 'btree_gist' and n.nspname <> 'extensions'
  ) then
    alter extension btree_gist set schema extensions;
  end if;
end
$migration$;

create schema if not exists locaux_dash;
create schema if not exists locaux_private;

revoke all on schema locaux_dash from public;
revoke all on schema locaux_private from public;

set local search_path = pg_catalog, locaux_dash, locaux_private, extensions;

do $migration$
begin
  create type locaux_dash.profile_role as enum ('manager', 'planner');
exception when duplicate_object then null;
end
$migration$;

do $migration$
begin
  create type locaux_dash.activity_status as enum ('planned', 'running', 'paused', 'complete', 'cancelled');
exception when duplicate_object then null;
end
$migration$;

do $migration$
begin
  create type locaux_dash.delay_category as enum (
    'none', 'panne', 'attente_reglage', 'changement_format', 'nettoyage', 'uncategorized'
  );
exception when duplicate_object then null;
end
$migration$;

create table if not exists locaux_dash.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role locaux_dash.profile_role not null default 'manager',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_display_name_chk check (
    display_name is null or char_length(btrim(display_name)) between 1 and 120
  )
);

create table if not exists locaux_dash.rooms (
  id bigint generated by default as identity primary key,
  name text not null,
  zone text not null default 'Zone de production',
  code text not null default '',
  kind text not null default 'generique',
  hygiene text not null default 'propre' check (hygiene in ('propre', 'a_nettoyer')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists locaux_dash.activities (
  id text primary key,
  room_id bigint not null references locaux_dash.rooms(id) on update cascade on delete restrict,
  activity text not null,
  product text not null default '—',
  batch text not null default '—',
  team text not null default 'Équipe A',
  owner text not null default '—',
  plan_start timestamptz not null,
  plan_end timestamptz not null,
  actual_start timestamptz,
  actual_end timestamptz,
  progress smallint not null default 0 check (progress between 0 and 100),
  status locaux_dash.activity_status not null default 'planned',
  step text not null default '',
  comment text not null default '',
  delay_category locaux_dash.delay_category not null default 'none',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint locaux_act_plan_dates check (plan_end > plan_start),
  constraint activities_actual_dates_chk check (
    actual_start is null or actual_end is null or actual_end > actual_start
  ),
  constraint activities_complete_chk check (
    status <> 'complete' or (progress = 100 and actual_end is not null)
  )
);

create table if not exists locaux_dash.settings (
  id smallint primary key default 1 check (id = 1),
  hours_per_team numeric(4,2) not null default 8,
  weekday_teams smallint not null default 2,
  include_saturday boolean not null default false,
  saturday_teams smallint not null default 1,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists locaux_dash.change_log (
  id bigint generated always as identity primary key,
  entity_type text not null,
  entity_id text not null,
  action text not null,
  detail text not null default '',
  payload jsonb not null default '{}'::jsonb,
  changed_by uuid references auth.users(id) on delete set null,
  changed_at timestamptz not null default now()
);

create table if not exists locaux_dash.articles (
  code text primary key,
  label text not null,
  family text not null,
  unit text not null,
  default_qty numeric not null default 1,
  default_futs smallint not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint articles_code_chk check (char_length(btrim(code)) between 1 and 32),
  constraint articles_label_chk check (char_length(btrim(label)) between 1 and 200),
  constraint articles_family_chk check (family in ('MP', 'MF', 'SF', 'pochette', 'PF')),
  constraint articles_unit_chk check (char_length(btrim(unit)) between 1 and 40),
  constraint articles_default_qty_chk check (default_qty > 0),
  constraint articles_default_futs_chk check (default_futs >= 0)
);

create table if not exists locaux_dash.stock_movements (
  id text primary key,
  sens text not null check (sens in ('entree', 'sortie')),
  article_code text not null references locaux_dash.articles(code) on update cascade on delete restrict,
  batch text not null default '—',
  qty numeric not null check (qty > 0),
  unit text not null default 'u',
  futs smallint not null default 0 check (futs >= 0),
  place text not null default '',
  comment text not null default '',
  at timestamptz not null default now(),
  created_by uuid not null default auth.uid() references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Colonnes nouvelles sur le schema live; l'ancien by_role sera remplace par created_by.
alter table locaux_dash.stock_movements
  add column if not exists created_by uuid,
  add column if not exists updated_at timestamptz not null default now();

-- Contraintes absentes du premier deploiement live.
do $migration$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'locaux_dash.profiles'::regclass and conname = 'profiles_display_name_chk'
  ) then
    alter table locaux_dash.profiles add constraint profiles_display_name_chk check (
      display_name is null or char_length(btrim(display_name)) between 1 and 120
    );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'locaux_dash.rooms'::regclass and conname = 'rooms_name_chk'
  ) then
    alter table locaux_dash.rooms add constraint rooms_name_chk
      check (char_length(btrim(name)) between 1 and 120);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'locaux_dash.rooms'::regclass and conname = 'rooms_zone_chk'
  ) then
    alter table locaux_dash.rooms add constraint rooms_zone_chk
      check (char_length(btrim(zone)) between 1 and 120);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'locaux_dash.rooms'::regclass and conname = 'rooms_code_chk'
  ) then
    alter table locaux_dash.rooms add constraint rooms_code_chk
      check (char_length(code) <= 16);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'locaux_dash.rooms'::regclass and conname = 'rooms_kind_chk'
  ) then
    alter table locaux_dash.rooms add constraint rooms_kind_chk
      check (char_length(kind) between 1 and 40);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'locaux_dash.activities'::regclass and conname = 'activities_actual_dates_chk'
  ) then
    alter table locaux_dash.activities add constraint activities_actual_dates_chk check (
      actual_start is null or actual_end is null or actual_end > actual_start
    );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'locaux_dash.activities'::regclass and conname = 'activities_complete_chk'
  ) then
    alter table locaux_dash.activities add constraint activities_complete_chk check (
      status <> 'complete' or (progress = 100 and actual_end is not null)
    );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'locaux_dash.settings'::regclass and conname = 'settings_hours_per_team_chk'
  ) then
    alter table locaux_dash.settings add constraint settings_hours_per_team_chk
      check (hours_per_team between 1 and 12);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'locaux_dash.settings'::regclass and conname = 'settings_weekday_teams_chk'
  ) then
    alter table locaux_dash.settings add constraint settings_weekday_teams_chk
      check (weekday_teams between 1 and 4);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'locaux_dash.settings'::regclass and conname = 'settings_saturday_teams_chk'
  ) then
    alter table locaux_dash.settings add constraint settings_saturday_teams_chk
      check (saturday_teams between 1 and 4);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'locaux_dash.change_log'::regclass and conname = 'change_log_entity_type_chk'
  ) then
    alter table locaux_dash.change_log add constraint change_log_entity_type_chk
      check (entity_type in ('activity', 'room', 'settings', 'article', 'stock_movement'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'locaux_dash.change_log'::regclass and conname = 'change_log_action_chk'
  ) then
    alter table locaux_dash.change_log add constraint change_log_action_chk
      check (action in ('insert', 'update', 'delete'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'locaux_dash.stock_movements'::regclass and conname = 'stock_movements_futs_chk'
  ) then
    alter table locaux_dash.stock_movements add constraint stock_movements_futs_chk
      check (futs >= 0);
  end if;
end
$migration$;

-- MF est une famille stock A26 explicite dans le client.
alter table locaux_dash.articles drop constraint if exists articles_family_chk;
alter table locaux_dash.articles add constraint articles_family_chk
  check (family in ('MP', 'MF', 'SF', 'pochette', 'PF'));

-- Parc usine stable. Les personnalisations existantes ne sont pas ecrasees.
insert into locaux_dash.rooms(id, code, name, zone, kind, hygiene, is_active) values
  (1, 'A23', 'A23 — Box de process', 'Pesée + mélange + prélèvement', 'process', 'propre', true),
  (2, 'A27', 'A27 — Géluleuse', 'Remplissage gélules', 'geluleuse', 'propre', true),
  (3, 'A26', 'A26 — Stockage primaire', 'SF gélule remplie · MP pesée · MF', 'stock_primaire', 'propre', true),
  (4, 'A28', 'A28 — Blistéreuse', 'Conditionnement primaire · mise sous blister', 'blistereuse', 'propre', true),
  (5, 'D08', 'D08 — Cond. secondaire continuité', 'Mise en étui · continuité A28', 'cond_sec_continuite', 'propre', true),
  (6, 'D18', 'D18 — Cond. secondaire assemblage', 'Assemblage Combifor · stock pochettes en attente', 'cond_sec_assemblage', 'propre', true)
on conflict (id) do update set
  code = case when locaux_dash.rooms.code = '' then excluded.code else locaux_dash.rooms.code end,
  kind = case when locaux_dash.rooms.kind = 'generique' then excluded.kind else locaux_dash.rooms.kind end
where
  (locaux_dash.rooms.code = '' and locaux_dash.rooms.code is distinct from excluded.code)
  or (
    locaux_dash.rooms.kind = 'generique'
    and locaux_dash.rooms.kind is distinct from excluded.kind
  );

select setval(
  pg_get_serial_sequence('locaux_dash.rooms', 'id'),
  greatest(coalesce((select max(id) from locaux_dash.rooms), 1), 1),
  true
);

insert into locaux_dash.settings(id, hours_per_team, weekday_teams, include_saturday, saturday_teams)
values (1, 8, 2, false, 1)
on conflict (id) do nothing;

insert into locaux_dash.articles(code, label, family, unit, default_qty, default_futs, active) values
  ('FSF600', 'Aerofor 12 µg (SF / process)', 'SF', 'gélules', 360000, 10, true),
  ('FSF601', 'Réservé / inactif', 'SF', 'gélules', 360000, 10, false),
  ('FSF602', 'Aeronide 200 µg (SF / process)', 'SF', 'gélules', 360000, 10, true),
  ('FSF603', 'Aeronide 400 µg (SF / process)', 'SF', 'gélules', 360000, 10, true),
  ('FSF604', 'Pochette Aerofor 12 · pour Combifor 12/200', 'pochette', 'pochettes', 1, 0, true),
  ('FSF605', 'Pochette Aerofor 12 · pour Combifor 12/400', 'pochette', 'pochettes', 1, 0, true),
  ('FSF606', 'Pochette Aeronide 200 · pour Combifor 12/200', 'pochette', 'pochettes', 1, 0, true),
  ('FSF607', 'Pochette Aeronide 400 · pour Combifor 12/400', 'pochette', 'pochettes', 1, 0, true),
  ('MP9', 'MP / Mélange · 9 kg', 'MP', 'kg', 9, 0, true),
  ('PF600', 'AEROFOR 12 µg – BTE 30', 'PF', 'boîtes', 1, 0, true),
  ('PF601', 'AEROFOR 12 µg – BTE 60', 'PF', 'boîtes', 1, 0, true),
  ('PF602', 'AERONIDE 200 µg – BTE 60', 'PF', 'boîtes', 1, 0, true),
  ('PF603', 'AERONIDE 400 µg – BTE 60', 'PF', 'boîtes', 1, 0, true),
  ('PF604', 'COMBIFOR 400 µg / 12 µg – BTE 120', 'PF', 'boîtes', 1, 0, true),
  ('PF605', 'COMBIFOR 200 µg / 12 µg – BTE 120', 'PF', 'boîtes', 1, 0, true)
on conflict (code) do nothing;

-- Preserve les codes de mouvements historiques avant d'ajouter la FK articles.
insert into locaux_dash.articles(code, label, family, unit, default_qty, default_futs, active)
select distinct
  btrim(m.article_code),
  btrim(m.article_code),
  'SF',
  coalesce(nullif(btrim(m.unit), ''), 'u'),
  1,
  0,
  true
from locaux_dash.stock_movements m
where btrim(m.article_code) <> ''
on conflict (code) do nothing;

do $migration$
begin
  if exists (select 1 from locaux_dash.stock_movements where btrim(article_code) = '') then
    raise exception 'Migration refusee: stock_movements.article_code contient une valeur vide';
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'locaux_dash.stock_movements'::regclass
      and conname = 'stock_movements_article_code_fkey'
  ) then
    alter table locaux_dash.stock_movements
      add constraint stock_movements_article_code_fkey
      foreign key (article_code) references locaux_dash.articles(code)
      on update cascade on delete restrict;
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'locaux_dash.stock_movements'::regclass
      and conname = 'stock_movements_created_by_fkey'
  ) then
    alter table locaux_dash.stock_movements
      add constraint stock_movements_created_by_fkey
      foreign key (created_by) references auth.users(id) on delete restrict;
  end if;
end
$migration$;

-- Le premier deploiement n'avait pas de proprietaire. S'il existe des lignes,
-- elles sont attribuees au planner le plus ancien, sinon au premier membre.
update locaux_dash.stock_movements
set created_by = coalesce(
  (select id from locaux_dash.profiles where role = 'planner' order by created_at, id limit 1),
  (select id from locaux_dash.profiles order by created_at, id limit 1)
)
where created_by is null;

do $migration$
begin
  if exists (select 1 from locaux_dash.stock_movements where created_by is null) then
    raise exception 'Migration refusee: mouvements historiques sans membre auquel attribuer created_by';
  end if;
end
$migration$;

alter table locaux_dash.stock_movements
  alter column created_by set default auth.uid(),
  alter column created_by set not null;

-- Remplace le libelle de role historique par le proprietaire Auth verifiable.
alter table locaux_dash.stock_movements drop column if exists by_role;

-- Integrite et index utiles aux lectures du dashboard.
create unique index if not exists rooms_code_uidx
  on locaux_dash.rooms (upper(code)) where code <> '';
create index if not exists rooms_active_idx
  on locaux_dash.rooms (is_active);
create index if not exists activities_room_plan_idx
  on locaux_dash.activities (room_id, plan_start);
create index if not exists activities_updated_at_idx
  on locaux_dash.activities (updated_at);
create index if not exists profiles_role_idx
  on locaux_dash.profiles (role);
create index if not exists settings_updated_by_idx
  on locaux_dash.settings (updated_by) where updated_by is not null;
create index if not exists change_log_changed_at_idx
  on locaux_dash.change_log (changed_at desc);
create index if not exists change_log_changed_by_idx
  on locaux_dash.change_log (changed_by) where changed_by is not null;
create index if not exists articles_family_active_idx
  on locaux_dash.articles (family, active);
create index if not exists stock_movements_article_at_idx
  on locaux_dash.stock_movements (article_code, at desc);
create index if not exists stock_movements_created_by_idx
  on locaux_dash.stock_movements (created_by);

do $migration$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'locaux_dash.activities'::regclass
      and conname = 'locaux_activities_no_room_overlap'
  ) then
    alter table locaux_dash.activities
      add constraint locaux_activities_no_room_overlap
      exclude using gist (
        room_id with =,
        tstzrange(plan_start, plan_end, '[)') with &&
      ) where (status <> 'cancelled');
  end if;
end
$migration$;

-- Retire uniquement l'auto-provisionnement historique de ce dashboard.
drop trigger if exists on_auth_user_created_locaux on auth.users;
drop function if exists locaux_dash.handle_new_user();

create or replace function locaux_private.is_member()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, locaux_dash
as $function$
  select exists (
    select 1
    from locaux_dash.profiles p
    where p.id = (select auth.uid())
  );
$function$;

create or replace function locaux_private.is_planner()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, locaux_dash
as $function$
  select exists (
    select 1
    from locaux_dash.profiles p
    where p.id = (select auth.uid()) and p.role = 'planner'
  );
$function$;

create or replace function locaux_private.set_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog
as $function$
begin
  new.updated_at := statement_timestamp();
  return new;
end;
$function$;

create or replace function locaux_private.set_settings_metadata()
returns trigger
language plpgsql
set search_path = pg_catalog
as $function$
begin
  new.updated_at := statement_timestamp();
  if auth.uid() is not null then
    new.updated_by := auth.uid();
  end if;
  return new;
end;
$function$;

create or replace function locaux_private.set_stock_owner()
returns trigger
language plpgsql
set search_path = pg_catalog
as $function$
begin
  if tg_op = 'INSERT' then
    if auth.uid() is not null then
      new.created_by := auth.uid();
    end if;
  else
    new.created_by := old.created_by;
  end if;
  return new;
end;
$function$;

create or replace function locaux_private.log_change()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, locaux_dash
as $function$
declare
  row_id text;
  entity text;
  data jsonb;
begin
  entity := case tg_table_name
    when 'activities' then 'activity'
    when 'rooms' then 'room'
    when 'settings' then 'settings'
    when 'articles' then 'article'
    when 'stock_movements' then 'stock_movement'
    else tg_table_name
  end;

  data := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  row_id := coalesce(data ->> 'id', data ->> 'code', '1');

  insert into locaux_dash.change_log(
    entity_type, entity_id, action, detail, payload, changed_by
  ) values (
    entity,
    row_id,
    lower(tg_op),
    format('%s %s', entity, lower(tg_op)),
    case when tg_op = 'UPDATE'
      then jsonb_build_object('old', to_jsonb(old), 'new', to_jsonb(new))
      else jsonb_build_object(lower(tg_op), data)
    end,
    auth.uid()
  );

  return case when tg_op = 'DELETE' then old else new end;
end;
$function$;

drop trigger if exists profiles_set_updated_at on locaux_dash.profiles;
create trigger profiles_set_updated_at
before update on locaux_dash.profiles
for each row execute function locaux_private.set_updated_at();

drop trigger if exists rooms_set_updated_at on locaux_dash.rooms;
create trigger rooms_set_updated_at
before update on locaux_dash.rooms
for each row execute function locaux_private.set_updated_at();

drop trigger if exists activities_set_updated_at on locaux_dash.activities;
create trigger activities_set_updated_at
before update on locaux_dash.activities
for each row execute function locaux_private.set_updated_at();

drop trigger if exists settings_set_update_metadata on locaux_dash.settings;
create trigger settings_set_update_metadata
before insert or update on locaux_dash.settings
for each row execute function locaux_private.set_settings_metadata();

drop trigger if exists articles_set_updated_at on locaux_dash.articles;
create trigger articles_set_updated_at
before update on locaux_dash.articles
for each row execute function locaux_private.set_updated_at();

drop trigger if exists stock_set_owner on locaux_dash.stock_movements;
create trigger stock_set_owner
before insert or update on locaux_dash.stock_movements
for each row execute function locaux_private.set_stock_owner();

drop trigger if exists stock_set_updated_at on locaux_dash.stock_movements;
create trigger stock_set_updated_at
before update on locaux_dash.stock_movements
for each row execute function locaux_private.set_updated_at();

drop trigger if exists rooms_change_log on locaux_dash.rooms;
create trigger rooms_change_log
after insert or update or delete on locaux_dash.rooms
for each row execute function locaux_private.log_change();

drop trigger if exists activities_change_log on locaux_dash.activities;
create trigger activities_change_log
after insert or update or delete on locaux_dash.activities
for each row execute function locaux_private.log_change();

drop trigger if exists settings_change_log on locaux_dash.settings;
create trigger settings_change_log
after insert or update or delete on locaux_dash.settings
for each row execute function locaux_private.log_change();

drop trigger if exists articles_change_log on locaux_dash.articles;
create trigger articles_change_log
after insert or update or delete on locaux_dash.articles
for each row execute function locaux_private.log_change();

drop trigger if exists stock_change_log on locaux_dash.stock_movements;
create trigger stock_change_log
after insert or update or delete on locaux_dash.stock_movements
for each row execute function locaux_private.log_change();

-- RLS: un compte Auth sans ligne profiles n'est pas membre et ne voit rien.
alter table locaux_dash.profiles enable row level security;
alter table locaux_dash.rooms enable row level security;
alter table locaux_dash.activities enable row level security;
alter table locaux_dash.settings enable row level security;
alter table locaux_dash.change_log enable row level security;
alter table locaux_dash.articles enable row level security;
alter table locaux_dash.stock_movements enable row level security;

-- Supprime aussi les anciennes politiques p_* permissives du deploiement live.
do $migration$
declare
  p record;
begin
  for p in
    select tablename, policyname
    from pg_policies
    where schemaname = 'locaux_dash'
      and tablename in (
        'profiles', 'rooms', 'activities', 'settings',
        'change_log', 'articles', 'stock_movements'
      )
  loop
    execute format('drop policy %I on locaux_dash.%I', p.policyname, p.tablename);
  end loop;
end
$migration$;

create policy profiles_self_or_planner_read
on locaux_dash.profiles for select to authenticated
using (
  (select locaux_private.is_member())
  and (id = (select auth.uid()) or (select locaux_private.is_planner()))
);

create policy rooms_member_read
on locaux_dash.rooms for select to authenticated
using ((select locaux_private.is_member()));
create policy rooms_planner_insert
on locaux_dash.rooms for insert to authenticated
with check ((select locaux_private.is_planner()));
create policy rooms_planner_update
on locaux_dash.rooms for update to authenticated
using ((select locaux_private.is_planner()))
with check ((select locaux_private.is_planner()));
create policy rooms_planner_delete
on locaux_dash.rooms for delete to authenticated
using ((select locaux_private.is_planner()));

create policy activities_member_read
on locaux_dash.activities for select to authenticated
using ((select locaux_private.is_member()));
create policy activities_planner_insert
on locaux_dash.activities for insert to authenticated
with check ((select locaux_private.is_planner()));
create policy activities_planner_update
on locaux_dash.activities for update to authenticated
using ((select locaux_private.is_planner()))
with check ((select locaux_private.is_planner()));
create policy activities_planner_delete
on locaux_dash.activities for delete to authenticated
using ((select locaux_private.is_planner()));

create policy settings_member_read
on locaux_dash.settings for select to authenticated
using ((select locaux_private.is_member()));
create policy settings_planner_insert
on locaux_dash.settings for insert to authenticated
with check ((select locaux_private.is_planner()));
create policy settings_planner_update
on locaux_dash.settings for update to authenticated
using ((select locaux_private.is_planner()))
with check ((select locaux_private.is_planner()));
create policy settings_planner_delete
on locaux_dash.settings for delete to authenticated
using ((select locaux_private.is_planner()));

create policy change_log_member_read
on locaux_dash.change_log for select to authenticated
using ((select locaux_private.is_member()));

create policy articles_member_read
on locaux_dash.articles for select to authenticated
using ((select locaux_private.is_member()));
create policy articles_planner_insert
on locaux_dash.articles for insert to authenticated
with check ((select locaux_private.is_planner()));
create policy articles_planner_update
on locaux_dash.articles for update to authenticated
using ((select locaux_private.is_planner()))
with check ((select locaux_private.is_planner()));
create policy articles_planner_delete
on locaux_dash.articles for delete to authenticated
using ((select locaux_private.is_planner()));

create policy stock_member_read
on locaux_dash.stock_movements for select to authenticated
using ((select locaux_private.is_member()));
create policy stock_member_insert_own
on locaux_dash.stock_movements for insert to authenticated
with check (
  (select locaux_private.is_member()) and created_by = (select auth.uid())
);
create policy stock_owner_or_planner_update
on locaux_dash.stock_movements for update to authenticated
using (
  (select locaux_private.is_member())
  and (created_by = (select auth.uid()) or (select locaux_private.is_planner()))
)
with check (
  (select locaux_private.is_member())
  and (created_by = (select auth.uid()) or (select locaux_private.is_planner()))
);
create policy stock_owner_or_planner_delete
on locaux_dash.stock_movements for delete to authenticated
using (
  (select locaux_private.is_member())
  and (created_by = (select auth.uid()) or (select locaux_private.is_planner()))
);

-- Grants Data API: authenticated seulement. RLS reste le controle effectif.
revoke all on schema locaux_dash from anon;
revoke all on schema locaux_private from anon;
revoke all on schema locaux_dash from authenticated;
revoke all on schema locaux_private from authenticated;
revoke all on all tables in schema locaux_dash from public, anon;
revoke all on all sequences in schema locaux_dash from public, anon;
revoke all on all tables in schema locaux_dash from authenticated;
revoke all on all sequences in schema locaux_dash from authenticated;
revoke all on all functions in schema locaux_dash from public, anon, authenticated;
revoke all on all functions in schema locaux_private from public, anon, authenticated;

grant usage on schema locaux_dash to authenticated, service_role;
grant usage on schema locaux_private to authenticated, service_role;

grant select on
  locaux_dash.profiles,
  locaux_dash.rooms,
  locaux_dash.activities,
  locaux_dash.settings,
  locaux_dash.change_log,
  locaux_dash.articles,
  locaux_dash.stock_movements
to authenticated;

grant insert, update, delete on
  locaux_dash.rooms,
  locaux_dash.activities,
  locaux_dash.settings,
  locaux_dash.articles,
  locaux_dash.stock_movements
to authenticated;

grant usage, select on sequence locaux_dash.rooms_id_seq to authenticated;
grant usage, select on sequence locaux_dash.change_log_id_seq to authenticated;
grant execute on function locaux_private.is_member() to authenticated;
grant execute on function locaux_private.is_planner() to authenticated;

grant all on all tables in schema locaux_dash to service_role;
grant all on all sequences in schema locaux_dash to service_role;

-- Realtime des six tables partagees; profiles reste hors publication.
alter table locaux_dash.rooms replica identity full;
alter table locaux_dash.activities replica identity full;
alter table locaux_dash.settings replica identity full;
alter table locaux_dash.change_log replica identity full;
alter table locaux_dash.articles replica identity full;
alter table locaux_dash.stock_movements replica identity full;

do $migration$
declare
  target regclass;
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    foreach target in array array[
      'locaux_dash.rooms'::regclass,
      'locaux_dash.activities'::regclass,
      'locaux_dash.settings'::regclass,
      'locaux_dash.change_log'::regclass,
      'locaux_dash.articles'::regclass,
      'locaux_dash.stock_movements'::regclass
    ]
    loop
      if not exists (
        select 1
        from pg_publication_rel pr
        join pg_publication p on p.oid = pr.prpubid
        where p.pubname = 'supabase_realtime' and pr.prrelid = target
      ) then
        execute format('alter publication supabase_realtime add table %s', target);
      end if;
    end loop;
  end if;
end
$migration$;

-- Verification transactionnelle minimale: un echec annule tout le script.
do $check$
declare
  rls_count integer;
  realtime_count integer;
begin
  select count(*) into rls_count
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'locaux_dash'
    and c.relname in (
      'profiles', 'rooms', 'activities', 'settings',
      'change_log', 'articles', 'stock_movements'
    )
    and c.relrowsecurity;

  if rls_count <> 7 then
    raise exception 'Verification RLS echouee: %/7 tables protegees', rls_count;
  end if;

  if exists (
    select 1 from pg_policies
    where schemaname = 'locaux_dash' and 'anon' = any(roles)
  ) then
    raise exception 'Verification RLS echouee: une politique anon subsiste';
  end if;

  if exists (
    select 1 from pg_trigger
    where tgrelid = 'auth.users'::regclass
      and not tgisinternal
      and tgname = 'on_auth_user_created_locaux'
  ) then
    raise exception 'Verification Auth echouee: auto-provisionnement encore actif';
  end if;

  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    select count(*) into realtime_count
    from pg_publication_rel pr
    join pg_publication p on p.oid = pr.prpubid
    join pg_class c on c.oid = pr.prrelid
    join pg_namespace n on n.oid = c.relnamespace
    where p.pubname = 'supabase_realtime'
      and n.nspname = 'locaux_dash'
      and c.relname in (
        'rooms', 'activities', 'settings', 'change_log', 'articles', 'stock_movements'
      );

    if realtime_count <> 6 then
      raise exception 'Verification Realtime echouee: %/6 tables publiees', realtime_count;
    end if;
  end if;
end
$check$;

commit;

-- Hors SQL: desactiver "Allow new users to sign up" dans Supabase Auth.
-- Ajouter ensuite les membres explicitement, puis leur profil avec role manager/planner.
